// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfaqop0cdBPI9VPSfbZlPrmy41e-_0z9M',
    appId: '1:357895086037:web:ceb30c2678b37fb81b275c',
    messagingSenderId: '357895086037',
    projectId: 'mad-voting-app',
    authDomain: 'mad-voting-app.firebaseapp.com',
    storageBucket: 'mad-voting-app.appspot.com',
    measurementId: 'G-SSEP81FQJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD012v2jQ2bJOlv0eyuH0QefAEay4hbovs',
    appId: '1:357895086037:android:d3c76e6d659855ca1b275c',
    messagingSenderId: '357895086037',
    projectId: 'mad-voting-app',
    storageBucket: 'mad-voting-app.appspot.com',
  );
}
